import { createHash } from 'node:crypto';
import { readFileSync, readdirSync } from 'node:fs';

import { deserializeCompactContractState } from '@midnight-ntwrk/midnight-js-utils';
import { describe, expect, it } from 'vitest';

import { STAGENET, hexToBytes } from '@evm-midnight-transparent/core';

import * as Vault from '../src/vendor/vault/Erc20Vault/contract/index.js';
import * as Signet from '../src/vendor/vault/SignetSigner/contract/index.js';

import { fixture, type VaultFixture } from './helpers.js';

// The vendored vault modules (src/vendor/vault/PROVENANCE.md): byte for byte what compactc 0.34.0
// generated from the vault at 6c7505a, and consistent with the vault deployed on stagenet.

const sha256 = (b: Uint8Array | string) => createHash('sha256').update(b).digest('hex');
const vendored = (rel: string) => readFileSync(new URL(`../src/vendor/vault/${rel}`, import.meta.url));

const PINNED = {
  'Erc20Vault/contract/index.js': 'd98e12adb189430b1cc28ff3a6007d7007a7e3c86e718ac92cba51dab4359296',
  'Erc20Vault/contract/index.d.ts': '66081e5080c60d9d1fefe33f92b5e032b5b745196b7e14cae26e242a059b8021',
  'SignetSigner/contract/index.js': '61464470a693cda984e77062536450ccc5e9221ea5be68281a2784f75b5f6a95',
  'SignetSigner/contract/index.d.ts': '25c8e81566785af7a2c1f399fda9b8c4dba1de0c2f4e23b0cb8b9ad87183c36f',
  'Erc20Vault/contract/index.js.map': 'd503e23c5477f89684b04b5241062d0fa5576c88a8f1caf670217f385487465c',
  'SignetSigner/contract/index.js.map': 'd8849451e290129d164895f5509cf6df12844a9371b8694db05844fad95c86bc',
};

// The vault as deployed (acedward/passport @ 6c7505a `deployments/stagenet-vault-vk-baseline.json`)
// plus the MIP-0018 circuit project 00038 inserted by a maintenance update.
const DEPLOYED_VAULT_VKS = {
  abandonDeposit: 'b50ff3961af1dc904e5e2559a3a93f9a16abde58ea1a8154cd925562bf67a350',
  completeDeposit: '7a61ca4e09a63e4e7f713a3570f47c64e31c90d9a5301d6f454437550a44c90e',
  completeWithdraw: '33590f23466f75e046fc293e5f3669dade92797606d698e0ba1670697fc92776',
  initialise: '177e7feaef12c2f5acfebf711026bb19f4958e0cf45a6ea6261afa172c5a3d07',
  publishTokenMetadata: 'd75c5f4e4efb5aabec056336b17478d0d5d01ee52071d4d108f2616d837d2b27',
  refundWithdraw: '03fcc5a2ab10c95080e4d704c7cac2a072de389b0d0b3c8a66771e5775c57869',
  startDeposit: '92eecf2be3aae82c1771c5a7bd7f4a85e51b3fe11c6377e929b3b6b218094990',
  startWithdraw: '23c977cec9866eab96e3998d61af39d3812e299ccbcbd3fd9d4102fcc9b2717c',
};

describe('the vendored vault contract', () => {
  it('is byte for byte the pinned compiler output', () => {
    for (const [rel, want] of Object.entries(PINNED)) expect(sha256(vendored(rel)), rel).toBe(want);
  });

  it('was generated by compactc 0.34.0 for compact-runtime 0.19.0, with no key material beside it', () => {
    const js = vendored('Erc20Vault/contract/index.js').toString('utf8');
    expect(js).toContain("__compactRuntime.checkRuntimeVersion('0.19.0')");
    expect(js).toContain("from '../../SignetSigner/contract/index.js'");
    expect(Object.keys(PINNED).every((p) => !/keys|zkir|\.prover|\.verifier/.test(p))).toBe(true);
    const listed = (dir: string) => readdirSync(new URL(`../src/vendor/vault/${dir}`, import.meta.url)).sort();
    expect(listed('Erc20Vault/contract')).toEqual(['index.d.ts', 'index.js', 'index.js.map']);
    expect(listed('SignetSigner/contract')).toEqual(['index.d.ts', 'index.js', 'index.js.map']);
    expect(listed('.')).toEqual(['Erc20Vault', 'PROVENANCE.md', 'SignetSigner']);
  });

  it("records every circuit's verifier-key fingerprint as deployed", () => {
    expect(Vault.expectedVk).toEqual(DEPLOYED_VAULT_VKS);
  });

  it('matches the verifier keys in the recorded stagenet state, for the vault and the Signet singleton', () => {
    const f = fixture<VaultFixture>('stagenet-vault-679357.json');
    expect(f.vault.address).toBe(STAGENET.bridge.vaultAddress);
    expect(f.singleton.address).toBe(STAGENET.bridge.signetSingleton);
    const ctx = { caller: 'test' };
    const vault = deserializeCompactContractState(hexToBytes(f.vault.state), ctx);
    for (const [circuit, want] of Object.entries(Vault.expectedVk as Record<string, string>)) {
      expect(sha256(vault.operation(circuit)!.verifierKey), circuit).toBe(want);
    }
    const singleton = deserializeCompactContractState(hexToBytes(f.singleton.state), ctx);
    const signetVks = Signet.expectedVk as Record<string, string>;
    expect(Object.keys(signetVks).sort()).toEqual(['respond', 'respondBidirectional', 'signBidirectional']);
    for (const [circuit, want] of Object.entries(signetVks)) {
      expect(sha256(singleton.operation(circuit)!.verifierKey), circuit).toBe(want);
    }
  });
});
